let Yup = require("yup");
export const createSenderIdInitialFormValues = {
  country: "",
  sender_name: "",
  isActive: false,
  Vodacom: {
    vodacom: "",
    tigo: "",
    airtel: "",
    halotel: "",
    zantel: "",
    ttcl: "",
    smile: "",
  },
  Tigo: {
    vodacom: "",
    tigo: "",
    airtel: "",
    halotel: "",
    zantel: "",
    ttcl: "",
    smile: "",
  },
  Airtel: {
    vodacom: "",
    tigo: "",
    airtel: "",
    halotel: "",
    zantel: "",
    ttcl: "",
    smile: "",
  },
  Halotel: {
    vodacom: "",
    tigo: "",
    airtel: "",
    halotel: "",
    zantel: "",
    ttcl: "",
    smile: "",
  },
  Zantel: {
    vodacom: "",
    tigo: "",
    airtel: "",
    halotel: "",
    zantel: "",
    ttcl: "",
    smile: "",
  },
  Ttcl: {
    vodacom: "",
    tigo: "",
    airtel: "",
    halotel: "",
    zantel: "",
    ttcl: "",
    smile: "",
  },
  Smile: {
    vodacom: "",
    tigo: "",
    airtel: "",
    halotel: "",
    zantel: "",
    ttcl: "",
    smile: "",
  },
};

export const formValuesValidation = Yup.object().shape({
  sender_id_country: Yup.string().required("Country required"),
  sender_name: Yup.string().required("Sender name is required"),
});
